package com.hb.model;


// Generated Dec 5, 2017 9:22:12 AM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HouseBoardTask generated by hbm2java
 */
@Entity
@Table(name = "house_board_task", catalog = "houseboard")
public class HouseBoardTask implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1492924370021225745L;
	private Integer id;
	private GroupDetails groupDetails;
	private SignUp signUp;
	private Date dateTime;
	private String taskSummary;
	private String taskDescription;
	private String fileAttached;
	private String taskStatus;
	private String taskStatusComment;
	private String taskStatusFile;

	public HouseBoardTask() {
	}

	public HouseBoardTask(GroupDetails groupDetails, SignUp signUp, Date dateTime, String taskSummary) {
		this.groupDetails = groupDetails;
		this.signUp = signUp;
		this.dateTime = dateTime;
		this.taskSummary = taskSummary;
	}

	public HouseBoardTask(GroupDetails groupDetails, SignUp signUp, Date dateTime, String taskSummary,
			String taskDescription, String fileAttached, String taskStatus, String taskStatusComment,
			String taskStatusFile) {
		this.groupDetails = groupDetails;
		this.signUp = signUp;
		this.dateTime = dateTime;
		this.taskSummary = taskSummary;
		this.taskDescription = taskDescription;
		this.fileAttached = fileAttached;
		this.taskStatus = taskStatus;
		this.taskStatusComment = taskStatusComment;
		this.taskStatusFile = taskStatusFile;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUP_ID", nullable = false)
	public GroupDetails getGroupDetails() {
		return this.groupDetails;
	}

	public void setGroupDetails(GroupDetails groupDetails) {
		this.groupDetails = groupDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASSIGNED_TO", nullable = false)
	public SignUp getSignUp() {
		return this.signUp;
	}

	public void setSignUp(SignUp signUp) {
		this.signUp = signUp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_TIME", nullable = false, length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "TASK_SUMMARY", nullable = false, length = 200)
	public String getTaskSummary() {
		return this.taskSummary;
	}

	public void setTaskSummary(String taskSummary) {
		this.taskSummary = taskSummary;
	}

	@Column(name = "TASK_DESCRIPTION", length = 1000)
	public String getTaskDescription() {
		return this.taskDescription;
	}

	public void setTaskDescription(String taskDescription) {
		this.taskDescription = taskDescription;
	}

	@Column(name = "FILE_ATTACHED", length = 200)
	public String getFileAttached() {
		return this.fileAttached;
	}

	public void setFileAttached(String fileAttached) {
		this.fileAttached = fileAttached;
	}

	@Column(name = "TASK_STATUS", length = 45)
	public String getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(String taskStatus) {
		this.taskStatus = taskStatus;
	}

	@Column(name = "TASK_STATUS_COMMENT", length = 500)
	public String getTaskStatusComment() {
		return this.taskStatusComment;
	}

	public void setTaskStatusComment(String taskStatusComment) {
		this.taskStatusComment = taskStatusComment;
	}

	@Column(name = "TASK_STATUS_FILE", length = 200)
	public String getTaskStatusFile() {
		return this.taskStatusFile;
	}

	public void setTaskStatusFile(String taskStatusFile) {
		this.taskStatusFile = taskStatusFile;
	}

}
